#!/usr/bin/env bash
# E7 end to end: capture and analyse, both themes, into E07/E07.txt — so the row can be regenerated by running
# one thing instead of being assembled by hand (gate finding).
# usage: e7.sh <out dir> <held tile id>
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/assert.sh"
source "$HERE/layout.sh"
OUT=$1; TILE=$2
mkdir -p "$OUT"
# Absolute: the analysers are invoked from the scripts directory, so a repo-relative path would not resolve.
OUT="$(cd "$OUT" && pwd)"
LOG=$OUT/E07.txt
: > "$LOG"
build_guard

{
  echo "# E7 — edit-mode geometry and motion, $(date -Iseconds)"
  echo "driver blobs: e7.sh $(git hash-object "$HERE/e7.sh") capture $(git hash-object "$HERE/e7_capture.sh")" \
       "geometry $(git hash-object "$HERE/e7_geometry.py") motion $(git hash-object "$HERE/e7_motion.py")" \
       "bracket $(git hash-object "$HERE/e7_bracket.py") latency $(git hash-object "$HERE/e7_latency.py")"
  echo
  echo "## Method"
  echo "Geometry from screencap pixels; motion from screenrecord frames with a sub-pixel edge, measured on"
  echo "every measurable tile and judged on the median; the exit latency from the shell's own ring buffer,"
  echo "which timestamps the touch-up's MotionEvent and the exit's first frame on one clock."
} >> "$LOG"

# Each theme pass starts from the baseline (PLAN RV12). This row used to run on whatever Start the device
# showed, and the dark pass's own 740-ms tap on the held tile made that app the promoted "last opened" tile,
# so the light pass held a tile that was no longer in the grid (2026-09-22 suite). layout_restore restarts the
# shell, which also clears the in-memory promotion.
layout_save "$OUT/layout_before.json"
for THEME in dark light; do
  echo >> "$LOG"; echo "## Theme: $THEME" >> "$LOG"
  layout_restore "$HERE/../baseline_layout.json" || say "FAIL could not seed the baseline for the $THEME pass"
  bash "$HERE/e7_capture.sh" "$OUT/$THEME" "$TILE" "$THEME" >> "$LOG" 2>&1
  # Two more entry recordings: the emulator's frame cadence moves these timings by ~20 % run to run, so the
  # row is judged on the median across runs as well as across tiles (gate finding: one run, one hand-picked
  # tile, decided the verdict).
  for RUN in 2 3; do
    bash "$HERE/e7_entry_only.sh" "$OUT/$THEME" "$TILE" "$RUN" >> "$LOG" 2>&1
  done
  echo >> "$LOG"; echo "### Geometry ($THEME)" >> "$LOG"
  ( cd "$HERE" && python3 e7_geometry.py "$OUT/$THEME" "$TILE" --theme "$THEME" ) >> "$LOG" 2>&1
  check "geometry ($THEME)" 0 $?
  echo >> "$LOG"; echo "### Hold bracket ($THEME)" >> "$LOG"
  ( cd "$HERE" && python3 e7_bracket.py "$OUT/$THEME" "$TILE" ) >> "$LOG" 2>&1
  check "hold bracket ($THEME)" 0 $?
  echo >> "$LOG"; echo "### Entry motion ($THEME), median over 3 recordings" >> "$LOG"
  ( cd "$HERE" && python3 e7_motion.py entry "$OUT/$THEME" --runs 3 ) >> "$LOG" 2>&1
  check "entry motion ($THEME)" 0 $?
  echo >> "$LOG"; echo "### Exit motion ($THEME)" >> "$LOG"
  ( cd "$HERE" && python3 e7_motion.py exit "$OUT/$THEME" ) >> "$LOG" 2>&1
  check "exit motion ($THEME)" 0 $?
  echo >> "$LOG"; echo "### Exit latency from the ring buffer ($THEME)" >> "$LOG"
  ( cd "$HERE" && python3 e7_latency.py "$OUT/$THEME/e7_edit_diag.txt" ) >> "$LOG" 2>&1
  check "exit latency ($THEME)" 0 $?
done

layout_restore "$OUT/layout_before.json" && say "restored: the device's own layout from before the row"
qa_finish
