INSTRUMENTATION_STATUS: gesture.script.cmd.0=down 268 2042
INSTRUMENTATION_STATUS: gesture.script.start.0=628155
INSTRUMENTATION_STATUS: gesture.script.cmd.1=moveto 268 2182 80 4
INSTRUMENTATION_STATUS: gesture.script.start.1=628187
INSTRUMENTATION_STATUS: gesture.script.cmd.2=sleep 900
INSTRUMENTATION_STATUS: gesture.script.start.2=628285
INSTRUMENTATION_STATUS: gesture.script.cmd.3=up
INSTRUMENTATION_STATUS: gesture.script.start.3=629136
