INSTRUMENTATION_STATUS: gesture.script.cmd.0=down 268 2042
INSTRUMENTATION_STATUS: gesture.script.start.0=601884
INSTRUMENTATION_STATUS: gesture.script.cmd.1=moveto 128 2042 80 4
INSTRUMENTATION_STATUS: gesture.script.start.1=601904
INSTRUMENTATION_STATUS: gesture.script.cmd.2=sleep 1050
INSTRUMENTATION_STATUS: gesture.script.start.2=602002
INSTRUMENTATION_STATUS: gesture.script.cmd.3=up
INSTRUMENTATION_STATUS: gesture.script.start.3=603014
