INSTRUMENTATION_STATUS: gesture.script.cmd.0=down 268 2042
INSTRUMENTATION_STATUS: gesture.script.start.0=1317645
INSTRUMENTATION_STATUS: gesture.script.cmd.1=moveto 408 2042 80 4
INSTRUMENTATION_STATUS: gesture.script.start.1=1317672
INSTRUMENTATION_STATUS: gesture.script.cmd.2=sleep 600
INSTRUMENTATION_STATUS: gesture.script.start.2=1317769
INSTRUMENTATION_STATUS: gesture.script.cmd.3=up
INSTRUMENTATION_STATUS: gesture.script.start.3=1318325
