INSTRUMENTATION_STATUS: gesture.script.cmd.0=down 268 2042
INSTRUMENTATION_STATUS: gesture.script.start.0=624145
INSTRUMENTATION_STATUS: gesture.script.cmd.1=moveto 268 1902 80 4
INSTRUMENTATION_STATUS: gesture.script.start.1=624169
INSTRUMENTATION_STATUS: gesture.script.cmd.2=sleep 900
INSTRUMENTATION_STATUS: gesture.script.start.2=624268
INSTRUMENTATION_STATUS: gesture.script.cmd.3=up
INSTRUMENTATION_STATUS: gesture.script.start.3=625125
