INSTRUMENTATION_STATUS: gesture.script.cmd.0=down 268 2042
INSTRUMENTATION_STATUS: gesture.script.start.0=1335571
INSTRUMENTATION_STATUS: gesture.script.cmd.1=moveto 268 1902 80 4
INSTRUMENTATION_STATUS: gesture.script.start.1=1335605
INSTRUMENTATION_STATUS: gesture.script.cmd.2=sleep 900
INSTRUMENTATION_STATUS: gesture.script.start.2=1335702
INSTRUMENTATION_STATUS: gesture.script.cmd.3=up
INSTRUMENTATION_STATUS: gesture.script.start.3=1336551
