#!/usr/bin/env python3
"""Phase 16 — the gate's evidence table, read from the run folders (never from memory).

For every row id it lists each kept run folder (<ROW> or <ROW>-<what the run was>) with the APK the run's log names,
its summary line and its FAIL count, and marks the ONE run that is the row's evidence: the newest run on the gate's
build with 0 failed (or, for a row named in E21/builds.txt, on the build named there). A row with no such run is
printed as OPEN. EDGE is listed per sub-step from the runs' logs.

    gate_evidence.py <gate build md5 prefix> > review/<date>-phase16-gate-evidence.md
"""
import os
import re
import sys

QA = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
GATE = sys.argv[1]
ROWS = ["E1", "E1_CHILDREN"] + ["E%d" % n for n in range(2, 29)] + ["E15_APK", "TRUST", "EDGE", "T2SMOKE"]

# E21/builds.txt: "<md5 prefix> <row|*> <why>" — a run on that earlier build stands for that row ("*": for every row).
# E21/rerun.txt: "<row> <why>" — a row whose code a later fix touched: only a run on the gate build counts for it.
also = {}
bt = os.path.join(QA, "E21", "builds.txt")
if os.path.exists(bt):
    for line in open(bt, encoding="utf-8"):
        if line.strip() and not line.startswith("#"):
            sha, row, why = line.split(None, 2)
            also.setdefault(row, []).append((sha, why.strip()))
rerun = {}
rt = os.path.join(QA, "E21", "rerun.txt")
if os.path.exists(rt):
    for line in open(rt, encoding="utf-8"):
        if line.strip() and not line.startswith("#"):
            row, why = line.split(None, 1)
            rerun[row] = why.strip()


def builds_for(row):
    if row in rerun:
        return [(GATE, "")]
    return [(GATE, "")] + also.get(row, []) + also.get("*", [])


def runs(row):
    out = []
    for name in sorted(os.listdir(QA)):
        d = os.path.join(QA, name)
        if not os.path.isdir(d) or not (name == row or name.startswith(row + "-")):
            continue
        log = os.path.join(d, row + ".txt")
        if not os.path.exists(log):
            continue
        text = open(log, encoding="utf-8", errors="replace").read()
        apk = re.search(r"^apk installed (\S+)", text, re.M)
        at = re.search(r"^at\s+(\S+)", text, re.M)
        summ = re.findall(r"^\s*%s: (\d+) passed, (\d+) failed, (\d+) recorded" % re.escape(row), text, re.M)
        only = re.search(r"(EDGE_ONLY|TRUST_ONLY)=(\S+?):", text)
        out.append({
            "dir": name, "apk": apk.group(1) if apk else "?", "at": at.group(1) if at else "?",
            "sum": summ[-1] if summ else None, "fails": len(re.findall(r"^FAIL ", text, re.M)),
            "only": only.group(2) if only else "", "mtime": os.path.getmtime(log), "text": text,
        })
    return sorted(out, key=lambda r: r["mtime"])


print("# Phase 16 — the gate's evidence, one line per kept run (generated by qa/phase-16/scripts/gate_evidence.py)\n")
print("Gate build: `%s`. A row's evidence is its newest run on that build with 0 failed; `E21/builds.txt` names the rows" % GATE)
print("whose run on an earlier build stands (the owner's ruling of 2026-10-01, \"only test the fixes\").\n")
print("| row | evidence run | result | other kept runs (oldest first) |")
print("|---|---|---|---|")
open_rows = []
for row in ROWS:
    rs = runs(row)
    if not rs and row in ("E1_CHILDREN", "T2SMOKE", "E21"):
        continue
    wants = builds_for(row)
    want = " / ".join(w[0][:8] for w in wants)
    good = [r for r in rs if any(r["apk"].startswith(w[0]) for w in wants) and r["sum"] and r["sum"][1] == "0" and not r["only"]]
    ev = good[-1] if good else None
    others = []
    for r in rs:
        if r is ev:
            continue
        s = "%s/%s/%s" % r["sum"] if r["sum"] else "no summary"
        others.append("`%s` %s on %s%s" % (r["dir"], s, r["apk"][:8], (" only=" + r["only"]) if r["only"] else ""))
    if ev:
        why = [w[1] for w in wants if w[1] and ev["apk"].startswith(w[0])]
        note = " (build %s: %s)" % (ev["apk"][:8], why[0][:110]) if why and not ev["apk"].startswith(GATE) else ""
        print("| %s | `%s/` %s | %s passed, %s failed, %s recorded%s | %s |" % (
            row, ev["dir"], ev["at"], ev["sum"][0], ev["sum"][1], ev["sum"][2], note, "; ".join(others) or "–"))
    else:
        open_rows.append(row)
        print("| %s | **OPEN** | no run on %s with 0 failed%s | %s |" % (
            row, want, (" (must be on the gate build: " + rerun[row][:90] + ")") if row in rerun else "", "; ".join(others) or "none"))

# EDGE per sub-step: the newest PASS / FAIL verdict lines that name the sub-step, over every EDGE run on the gate build.
idx = os.path.join(QA, "scripts", "edge_index.tsv")
if os.path.exists(idx):
    ids = []
    for line in open(idx, encoding="utf-8"):
        ids += re.findall(r"\b([CP]\d\d)\b", line)
    ids = sorted(set(ids))
    print("\n## EDGE sub-steps (from every EDGE run on the gate build, grouped and single)\n")
    print("| sub-step | newest run that ran it | PASS lines | FAIL lines |")
    print("|---|---|---|---|")
    edge_runs = []
    for root, _dirs, files in os.walk(QA):
        for f in files:
            if re.match(r"EDGE.*\.txt$", f) and "ring" not in f:
                p = os.path.join(root, f)
                t = open(p, encoding="utf-8", errors="replace").read()
                if any(re.search(r"^apk installed %s" % re.escape(w[0]), t, re.M) for w in builds_for("EDGE")):
                    edge_runs.append((os.path.getmtime(p), os.path.relpath(p, QA), t))
    edge_runs.sort()
    for i in ids:
        hit = None
        for _m, rel, t in edge_runs:
            ps = len(re.findall(r"^PASS\s+%s\b" % i, t, re.M)); fs = len(re.findall(r"^FAIL\s+%s\b" % i, t, re.M))
            if ps or fs:
                hit = (rel, ps, fs)
        if hit:
            print("| %s | `%s` | %d | %d |" % (i, hit[0], hit[1], hit[2]))
            if hit[2]:
                open_rows.append("EDGE " + i)
        else:
            print("| %s | **OPEN** — no run on the gate build | – | – |" % i)
            open_rows.append("EDGE " + i)

print("\n## Open: %s" % (", ".join(open_rows) if open_rows else "nothing"))
